### ISSUE TITLE
Management - Group Bonding Event

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#1]
# Task List
- [x] @everyone - Fill out the When2Meet "general availability form"
- [x] Set up a meeting time for Group Bonding Event (Wednesday 4:00 to 5:30 pm)
- [x] Take Screenshot of Zoom Call and Submit to Canvas 

---

## Description
![image](https://user-images.githubusercontent.com/56616495/136888543-dc3cd92c-c592-420f-9cc8-ed6e1a43696b.png)
