### ISSUE TITLE
HTML - Login Page/Account  Creation Page

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#10]
# Task List Account Creation
- [x] Same format as home page. (see  wireframes)
- [x] Put the logo on the homepage @Dorsa-lucky 
- [x] Textbox form for username
- [x] Textbox form for email
- [x] textbox form for password
- [x] Textbox form for confirm password 
- [x] Button for sign up
- [x] Button for cancel (leads back to home page)

# Task List Login page
- [x] Textbox for username
- [x] Textbox for password
- [x] Log in button
- [x] cancel button

**Comment by Dorsa-lucky** [comment]
added logo to the home-page html
