### ISSUE TITLE
SPA for Home Page (Loading in HTML Skeleton for Recipe Cards and  Recipe Expand)

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#13]
**Task List**
- [x] Use recipe json data (from labs) for now, use the data to populate the HTML skeleton for Recipe Card
- [x] Load the recipe card to home page skeleton
- [x] #46

- [x] Use data from database to dynamically populate recipe cards
- [x] Create buttons/links to link to the login/create new recipe page. (if they try  to click on create new recipe, check if they are logged in first, if they are not logged in first redirect them to login page).
