### ISSUE TITLE
Creating a recipe .json from form answers 

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#14]
**Task List**
- [x] Using the user's input into the  recipe creation form, create a .json the same format as the labs.
- [x] For recipe updating, take a recipe .json and repopulate the form, allow the user to edit the fields as necessary.  @Yoomin99 
- [x] Figure out how  tags is going to be selected (how to add multiple tags via dropdown menu)
