### ISSUE TITLE
Management - Group Kickoff, Repo and Meeting Prep

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#2]
# Task List
- [x] Have a Kickoff  Meeting 
- [x] Create Meeting Notes and Put them on repo. 
- [x] Create directories in repo
- [x] Create README.md in root
- [x] Add a short description of project to README.md
- [x] Invite TA as a collaborator?
