### ISSUE TITLE
Management - Branding, Group Page and Video

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#3]
# Task List
- [x] Team Name
- [x] Team colors
- [x] Team Mascot (Scared Hamster)
- [x] Set Slack Workspace Icon to an image that represents our brand and incorporates our team number prominently
- [x] Finish Team Page
- [x] @everyone add a brief overview of yourself 
- [x] Team Intro Video, Discuss, Record, and Edit

---

# Description
![image](https://user-images.githubusercontent.com/56616495/136889669-8ebd457f-cfe1-4692-bfbd-5243fc858a14.png)

---
![image](https://user-images.githubusercontent.com/56616495/136889691-5ff7d18c-7dff-4892-a73e-ff8a930b4c80.png)
