### ISSUE TITLE
Management - Group Contract

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#4]
# Task List
- [x] Finish Final Draft of Contract @rubycmarroquin 
- [x] Convert Contract to Markdown Format @QuocVDo and upload to /admin/misc/rules.md
- [x] Sign contract and upload to to  /admin/misc/rules-**name**.pdf @everyone
- [x] Submit Screenshot of repo with all executed documents and rules. @rubycmarroquin
