### ISSUE TITLE
HTML - Homepage

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#6]
# Task List
- [x] Buttons/Navbar to navigate to other pages
- [x] Page Logo in top Left
- [x] Space for Recipe cards.
- [x] Search Bar
- [x] Log In button
- [x] Commit to Repo
