### ISSUE TITLE
HTML - Person's Page/My Account +  My Recipes

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#7]
# Task List
- [x] Add Logo in top left (placeholder)
- [x] Log in button.
- [x] Add recipe button
- [x] Section for created recipes
- [x] Section for pinned/saved/bookmarked recipes
- [x] Account settings Button

**Comment by JinnnyWinnny** [comment]
finished
