### ISSUE TITLE
HTML Recipe Card + Recipe Expand

### ISSUE THREAD

**Issue by QuocVDo** [cse110-fa21-group25/cse110-fa21-group25#9]
# Task List
- [ ] Layout of what our recipe cards/ expand look like (see Labs)
- [ ] Create HTML template about what the recipe card looks like
- [ ] Create HTML template about what the recipe expand looks like

---
* For our recipe card it should display an image, title, and ingredients list just like in the lab
* No spot for reviews at the moment
* A space where the username of the person who created the recipe.
* A space to put the time that it takes to make the recipe
* For recipe expand it should follow  similar format to the lab (leave it up to your discretion). Don't copy lab because we'll get screwed if we do.

**Comment by Lilith-Schreiber** [comment]
I have already pushed the templates
